import os
from google import genai
from dotenv import load_dotenv


class LLMExplainer:
    """
    Uses Gemini to generate a human-readable explanation
    for two legal clauses.

    Note:
    - This class does NOT perform contradiction detection.
    - Contradiction detection is handled by the fine-tuned
      DeBERTa NLI model.
    """

    def __init__(self):

        # Load environment variables
        load_dotenv()

        api_key = os.getenv("GEMINI_API_KEY")

        if api_key is None:
            raise ValueError(
                "GEMINI_API_KEY not found in .env file."
            )

        self.client = genai.Client(api_key=api_key)

    def explain(self, source_text: str, target_text: str) -> str:
        """
        Generate an explanation comparing two clauses.

        Parameters
        ----------
        source_text : str
            First clause.

        target_text : str
            Second clause.

        Returns
        -------
        str
            Natural language explanation generated by Gemini.
        """

        prompt = f"""
    You are an expert legal contract analyst.

    Analyze ONLY the two clauses provided below.

    Rules:
    - Use only the information contained in the clauses.
    - Do NOT assume the clauses contradict or support each other.
    - Do NOT classify them as contradiction, entailment, or neutral.
    - Do NOT mention AI models, machine learning, predictions, confidence scores, or classifiers.
    - Keep the response concise and practical.
    - Limit the response to approximately 150–200 words.

    ==================================================
    SOURCE CLAUSE
    ==================================================

    {source_text}

    ==================================================
    TARGET CLAUSE
    ==================================================

    {target_text}

    Provide your response using exactly the following format.

    ### Source Clause Summary
    Summarize the source clause in 1–2 sentences.

    ### Target Clause Summary
    Summarize the target clause in 1–2 sentences.

    ### Relationship Between Clauses
    Provide 3–4 concise bullet points covering:
    - The main common topic.
    - The key differences.
    - Any overlapping obligations, rights, or responsibilities.
    - Whether an explicit conflict is present. If none exists, clearly state that.

    ### Legal Risk
    State one of:
    - Low
    - Medium
    - High

    Then explain the risk in one concise sentence.

    Keep the explanation factual, objective, and easy for legal professionals to read.
    """
        try:

            response = self.client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt,
            )

            return response.text

        except Exception as e:

            return f"LLM explanation failed: {str(e)}"